@startuml
'https://plantuml.com/class-diagram
class Rectangle{
-width: double
-height: double

+Rectangle()
+Rectangle(width: double, height: double)
+getArea(): double
+getPerimeter(): double

}

object "rectangle1: Rectangle" as rectangle1{
width = 4
height = 40
}
object "rectangle2: Rectangle" as rectangle2{
width = 3.5
height = 35.9
}

Rectangle -down[hidden]-> rectangle1
Rectangle -down[hidden]-> rectangle2

@enduml